### ISSUE TITLE
Error importing DiffusionSampler

### ISSUE THREAD

**Issue by DimitrisAlivas** [benedekrozemberczki/littleballoffur#11]
Hello,

First of all, thank you for your great work building this library. Great extension to NetworkX.

I am facing an issue when trying to import the `DiffusionSampler` specifically. All the other samplers get imported just fine. However the `DiffusionSampler` raises import issue.

I am using a Jupyter notebook as an environment.

The specific error output: 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-29-fbd222d9c756> in <module>
----> 1 from littleballoffur import DiffusionSampler
      2 
      3 
      4 model = DiffusionSampler()
      5 new_graph = model.sample(wd50k_connected_relabeled)

ImportError: cannot import name 'DiffusionSampler' from 'littleballoffur'
```

Is this replicable? 

Thank you in advance for looking into it.

**Comment by benedekrozemberczki** [comment]
Dear Dimitris,

I started the sampler yesterday in the evening. I will finish it in a few
hours today. Do you plan to use the library and the sampler in a paper?

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
Dear @DimitrisAlivas,

I have added the diffusion sampler and tested it. The read the docs were updated accordingly. If you use the framework or the Diffusion Sampler in research please cite the paper about Little Ball of Fur and the Diffusion sampler:

```bibtex
>@inproceedings{rozemberczki2018fastsequence,  
  title={{Fast Sequence Based Embedding with Diffusion Graphs}},  
  author={Rozemberczki, Benedek and Sarkar, Rik},  
  booktitle={International Conference on Complex Networks},  
  year={2018},  
  pages={99--107}
 }
```

```bibtex
@inproceedings{littleballoffur,
               title={{Little Ball of Fur: A Python Library for Graph Sampling}},
               author={Benedek Rozemberczki and Oliver Kiss and Rik Sarkar},
               year={2020},
               pages = {3133–3140},
               booktitle={Proceedings of the 29th ACM International Conference on Information and Knowledge Management (CIKM '20)},
               organization={ACM},
}

If you feel like it please star the repo, follow me on GitHub and Twitter.

Bests,

Benedek

**Comment by DimitrisAlivas** [comment]
Hey Benedek,

Thanks, I will take a look later today.

Indeed, I've been experimenting/testing to see if your library fits my use case. Of course, if it ends up as a fit, I will ensure the proper citations are there :) 

Glad to connect with you. I've already starred the repo and followed you on GitHub & Twitter.

Cheers,
Dimitris
