### ISSUE TITLE
Node attributes are not copied from original graph

### ISSUE THREAD

**Issue by jungla88** [benedekrozemberczki/littleballoffur#12]
Breadth and Depth First Search return me subgraphs without correct attributes on nodes/edges. Actually, I found that the dict containing those attributes has been completely deleted in the sampled graph.
Is this a known issue? Is the sampler supposed to work in this way?

**Comment by benedekrozemberczki** [comment]
Most of the samplers behave that way as we are not subinducing the graph from the original graph object. You could use some reassignment I suppose. In the paper, we describe the assumptions about the graph. May I ask what is your use case?

**Comment by jungla88** [comment]
Thank you. I will read the paper. 
Anyway, I would like to use the sampler for graph classification.

**Comment by benedekrozemberczki** [comment]
What is the dataset that you are working with?

**Comment by jungla88** [comment]
Usually I work with TUdataset like AIDS,Mutagenicity, Proteins, Letter.

**Comment by jungla88** [comment]
Another issues from these two samplers: when max number of nodes is set to 1 the sampled subgraph is empty. I think it should return the root node of the traversal, which typically happen with RandomWalk samplers (both with and without restart)

**Comment by benedekrozemberczki** [comment]
Okay. I did the modification and added the appropriate tests.
