### ISSUE TITLE
Assumptions on graph properties

### ISSUE THREAD

**Issue by jungla88** [benedekrozemberczki/littleballoffur#13]
Hi there,

I am wondering if it would be possible to relax some constrain the graph has to satisfy in order to start an exploration on it.
In particular, the requirement of connectivity seems a bit strong to me. I think a graph sampling procedure could easily deal with such property, since in the case the graph is not connected the sampling could take place on the single connected components or the exploration could rely on the neighborhood of the current node explored.
For node sampling strategies like BFS and DFS looks pretty natural to me, also for Random Walk Sampling (maybe the one with the restart probability could be a little tricky). Something strange could probably happen for edge sampling if the connectivity property is not satisfied.
Do you see any possibility to extend little ball of fur to such type of graphs? What was the reason that bring you to assume the connectivity property for graphs?

Thank you !

**Comment by benedekrozemberczki** [comment]
If you think about it, such approach would need an in advance knowledge of
the structure of connected components and the size of the components. With
the current design you can do the following:

- 1. Decompose to connected components.
- 2. Sample from components which are connected.

**Comment by benedekrozemberczki** [comment]
May I ask what is your use case?

**Comment by jungla88** [comment]
I'm working on graph classification algorithms for general purpose application. This particular issues arise from datasets that are not really networks but come from computer vision field. They are Letter dataset and Grec. You can find in IAM repository and probably on TU dortmund repository. Anyway, I opened recently an issue an gives you the same information :).

Thank you for you answers and for your work which I really appreciate.
