### ISSUE TITLE
Why can't I use the graph imported by nx.read_edgelist()

### ISSUE THREAD

**Issue by DeathSentence** [benedekrozemberczki/littleballoffur#14]
graph = nx.read_edgelist("filename", nodetype=int, data=(("Weight", int),))

error : AssertionError: Graph is not connected.
why? 'graph' is a networkx graph

**Comment by benedekrozemberczki** [comment]
Did you read the paper?

**Comment by DeathSentence** [comment]
oh, i'm sorry to bother you.
I have found the reason because 'check_connectivity()'.
In your framework, the input graph must be connected.
Do all sampling algorithms must be based on connected graphs?

**Comment by benedekrozemberczki** [comment]
Not all. You can read the papers and decide.

**Comment by benedekrozemberczki** [comment]
Also you can execute sampling on the components if you know what I mean.
Could you star the repo and follow me on GitHub?

**Comment by DeathSentence** [comment]
> Could you star the repo and follow me on GitHub?

ok, thanks
