### ISSUE TITLE
Have a problem installing networkit version 7.1 in centos 

### ISSUE THREAD

**Issue by GaroBozadjian** [benedekrozemberczki/littleballoffur#20]
Problem installing networkit 7.1 in centos os

**Comment by Hsu1023** [comment]
I have the same problem in centos os

**Comment by benedekrozemberczki** [comment]
Could you provide more detail @GaroBozadjian and @Hsu1023 ?

**Comment by lestherll** [comment]
I had the same problem. I'm on `Linux 5.19.0-35-generic 22.04.1-Ubuntu`. I fixed it by essentially removing the version constraint for `networkit` (see below) in `setup.py`. Then I just pip installed the repo normally.

I don't have knowledge of the inner workings of `littleballoffur` to assess the implications of this but it works for my use case enough.

https://github.com/benedekrozemberczki/littleballoffur/compare/master...lestherll:littleballoffur:master

**Comment by rjurney** [comment]
@GaroBozadjian @Hsu1023 @lestherll I hope we are going to upgrade to networkit 10.1 soon, that should help this?
