### ISSUE TITLE
PageRankSampler and maybe the backend don't work if NetworkX node IDs aren't numeric

### ISSUE THREAD

**Issue by rjurney** [benedekrozemberczki/littleballoffur#24]
My graph loading code for the SNAP high energy physics paper arXiv DiGraph is as follows:

```python
import gzip
import io
import networkx as nx
import tarfile


# Initialize a directed graph
G = nx.DiGraph()

# Download and load edges (citations) from `cit-HepTh.txt.gz`
response = requests.get("https://snap.stanford.edu/data/cit-HepTh.txt.gz")
gzip_content = io.BytesIO(response.content)

# Decompress the gzip content and build the edge list for our network
with gzip.GzipFile(fileobj=gzip_content) as f:
    for line in f:
        line = line.decode('utf-8')
        # Ignore lines that start with '#'
        if not line.startswith('#'):
            cited, citing = line.strip().split('\t')
            G.add_edge(citing, cited)
```

My unit test is as follows:

```python
from littleballoffur import PageRankBasedSampler

pagerank_sampler = PageRankBasedSampler(number_of_nodes=G.number_of_nodes)
G_pagerank_sample = pagerank_sampler.sample(G.to_undirected())

print(f"Original citation graph nodes: {G.number_of_nodes:,}")
print(f"PageRank node sampled nodes: {G_pagerank_sample.number_of_nodes:,}")
```

My exception is in the NetworkX backend in the `NetworkXBackEnd._check_indexing(self, graph)` method, line 253:

```python
assert numeric_indices == node_indices, "The node indexing is wrong."
```

__I did not realize when updating this code that it would not work with non-text node IDs.__ I may start using numeric IDs with a map... if I did not introduce the bug in #23. Or I will fix this bug :) I will work on this tomorrow!

The full exception follows:

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[18], line 4
      1 from littleballoffur import PageRankBasedSampler
      3 pagerank_sampler = PageRankBasedSampler(number_of_nodes=G.number_of_nodes)
----> 4 G_pagerank_sample = pagerank_sampler.sample(G.to_undirected())
      6 print(f"Original citation graph nodes: {G.number_of_nodes:,}")
      7 print(f"PageRank node sampled nodes: {G_pagerank_sample.number_of_nodes:,}")

File /opt/conda/lib/python3.10/site-packages/littleballoffur/node_sampling/pagerankbasedsampler.py:51, in PageRankBasedSampler.sample(self, graph)
     41 def sample(self, graph: Union[NXGraph, NKGraph]) -> Union[NXGraph, NKGraph]:
     42     """
     43     Sampling nodes randomly proportional to the normalized pagerank score.
     44 
   (...)
     49         * **new_graph** *(NetworkX or NetworKit graph)* - The graph of sampled nodes.
     50     """
---> 51     self._deploy_backend(graph)
     52     self._check_number_of_nodes(graph)
     53     sampled_nodes = self._create_initial_node_set(graph)

File /opt/conda/lib/python3.10/site-packages/littleballoffur/sampler.py:37, in Sampler._deploy_backend(self, graph)
     35 elif isinstance(graph, NXGraph):
     36     self.backend = NetworkXBackEnd()
---> 37     self.backend.check_graph(graph)
     38 else:
     39     raise ValueError("Not a NetworKit or NetworkX graph.")

File /opt/conda/lib/python3.10/site-packages/littleballoffur/backend.py:259, in NetworkXBackEnd.check_graph(self, graph)
    257 self._check_networkx_graph(graph)
    258 self._check_directedness(graph)
--> 259 self._check_indexing(graph)

File /opt/conda/lib/python3.10/site-packages/littleballoffur/backend.py:253, in NetworkXBackEnd._check_indexing(self, graph)
    251 numeric_indices = [index for index in range(graph.number_of_nodes())]
    252 node_indices = sorted([node for node in graph.nodes()])
--> 253 assert numeric_indices == node_indices, "The node indexing is wrong."

AssertionError: The node indexing is wrong.
```

**Comment by benedekrozemberczki** [comment]
It was always designed like this!

**Comment by rjurney** [comment]
I see, so I should be creating my nodes to have sequential IDs and add a `label` or `dblp` field or some such for their DBLP IDs. Got it!

**Comment by rjurney** [comment]
I redid my IDs to use sequential integers and it still doesn't work... but I get a new error. Still looking at it!

**Comment by rjurney** [comment]
@benedekrozemberczki so this is a problem because you can make the node IDs numeric, but the value of the actual nodes has to be numeric as well - which means no properties. I want to use `littleballoffur` on Graphs with `dicts` assigned to the nodes. Can we pull this check? I don't think it is needed:

```python
    def _check_indexing(self, graph: NXGraph):
        """Checking the consecutive numeric indexing."""
        numeric_indices = [index for index in range(graph.number_of_nodes())]
        node_indices = sorted([node for node in graph.nodes()])
        assert numeric_indices == node_indices, "The node indexing is wrong."
```

**Comment by rjurney** [comment]
For example, here is ChatGPT on the matter:

To retrieve the indices of nodes in a NetworkX graph, you'd typically get the nodes of the graph and then enumerate them to assign each node an index. In many cases, however, nodes themselves can act as indices if they are already integers or some other form of identifiers.

Here's how you can retrieve the indices of nodes in a NetworkX graph:

1. **If nodes are already numbers (e.g., integers)**:
You can directly retrieve them using the `nodes()` method of the graph.

```python
import networkx as nx

G = nx.Graph()
G.add_nodes_from([0, 1, 2, 3, 4])
node_indices = list(G.nodes())
print(node_indices)
```

2. **If nodes are not numbers or you want to create an index for each node**:
You can enumerate the nodes to assign an index to each node.

```python
G = nx.Graph()
G.add_nodes_from(['A', 'B', 'C', 'D'])
node_indices = {node: idx for idx, node in enumerate(G.nodes())}
print(node_indices)
```

This will give you a dictionary where keys are nodes and values are their indices.

3. **To get just the list of indices** (based on the order of nodes in the graph):

```python
indices = list(range(len(G)))
print(indices)
```

You can then use these indices for various operations or mappings as needed.

**Comment by rjurney** [comment]
@benedekrozemberczki can you please reopen this ticket? I want to make things work with nodes that have properties by setting `graph.nodes(data=false)`, which will prevent properties from being returned. If that doesn’t work, I can loop over the first element returned by `graph.nodes.items()` for the same effect. This will make this library work with networkx graphs that have properties.

**Comment by rjurney** [comment]
Actually... this works now :) Moving it into my class in Part 2 - Network Science! :D
