### ISSUE TITLE
ForestFireSampler throws exceptions for some seed values

### ISSUE THREAD

**Issue by nrodday** [benedekrozemberczki/littleballoffur#8]
Hi,

I am trying to sample an undirected, connected graph of 5559 nodes and 10804 edges into a sample of 100 nodes. As I loop over the "creation of samples" part, I am altering the seed for the ForeFireSampler every time to obtain a different sample.

E.g.
seed_value = random.randint(1,2147483646)
sampler = ForestFireSampler(100, seed=seed_value )

However, for some runs I get an exception thrown, which is also reproducible. I assume it is related to specific seed values which the sampler doesn´t seem to be able to handle. An example is seed value 1176372277.

Traceback (most recent call last):
  File "/project/topology_extraction.py", line 472, in <module>
    abstraction_G = graph_sampling(S)
  File "/project/topology_extraction.py", line 234, in graph_sampling
    new_graph = sampler.sample(S)
  File "/usr/local/lib/python3.8/dist-packages/littleballoffur/exploration_sampling/forestfiresampler.py", line 74, in sample
    self._start_a_fire(graph)
  File "/usr/local/lib/python3.8/dist-packages/littleballoffur/exploration_sampling/forestfiresampler.py", line 47, in _start_a_fire
    top_node = node_queue.popleft()
IndexError: pop from an empty deque

Process finished with exit code 1

I believe this is a bug in the library.

Thanks!
Nils

**Comment by bricaud** [comment]
Hi,
This is not really a bug. See my answer on closed issue #6 
@benedekrozemberczki you may want to catch this error and display a message more informative than what is given.
Do you want me to make a PR about that?

Benjamin

**Comment by nrodday** [comment]
Hi Benjamin,

Thanks for your quick reply. I was just about to add that the likelihood increases tremendously when the number of nodes is increased - totally understandable with your explanation from https://github.com/benedekrozemberczki/littleballoffur/issues/6. Sry for not checking old issues first.

I think displaying a proper error message that the fire died and the number of sampled nodes could not be reached makes sense. Currently, I am just catching that error and looping again until I get a usable sample.

Cheers,
Nils

**Comment by benedekrozemberczki** [comment]
@bricaud Feel free to open a PR.

@nrodday It would be interesting to see the graph itself. It might be that restarting the fires causes the issue. Thanks for raising the issue!
